#!/usr/bin/env php
<?php

////////////////////////////////////////////
//
//  VOYAGER FRAMEWORK
//  ----------------------------------------
//  https://github.com/voyager-php/voyager
//
////////////////////////////////////////////
//
//  Version: v1.0.5
//  Author: James Crisostomo
//  Email: nerdlabenterprise@gmail.com
//
////////////////////////////////////////////

// Include composer autoload mechanism to
// import third party modules and libraries.

if(file_exists('vendor/autoload.php'))
{
    require 'vendor/autoload.php';
}

// Initiate console application.

Voyager\Console\Command::init($argv);