#!/usr/bin/env php
<?php

////////////////////////////////////////////
//
//  VOYAGER FRAMEWORK
//  ----------------------------------------
//  https://github.com/voyager-php/voyager
//
////////////////////////////////////////////
//
//  Version: v1.0.6
//  Author: James Crisostomo
//  Email: nerdlabenterprise@gmail.com
//
////////////////////////////////////////////

// Include composer autoload mechanism to
// import third party modules and libraries.
// If composer is not available, use the
// native autoload mechanism.

if(file_exists('vendor/autoload.php'))
{
    require 'vendor/autoload.php';
}
else
{
    $root = '';

    require 'autoload.php';
}

// Initiate console application.

Voyager\Console\Command::init($argv);